namespace: tap-dev
targetImagePullSecret: registry-credentials
snyk:
  tokenSecret:
    name: snyk-token-secret
metadataStore:
  url: https://metadata-store.tanzu.y-compiles.com
  caSecret:
    name: store-ca-cert
    importFromNamespace: "" #! since both snyk and grype both enable store, one must leave importFromNamespace blank
  authSecret:
    name: store-auth-token
    importFromNamespace: "" #! since both snyk and grype both enable store, one must leave importFromNamespace blank
