#@data/values

#@overlay/match-child-defaults missing_ok=True
---
tap:
  version: "1.1.0-build.17"
  namespace: tap-install
  catalogs: []

  registry:
    host: tapbuild.azurecr.io
    repositories:
      buildService: repo/build-service
      ootbSupplyChain: repo/supply-chain

  domains:
    main: tap.y-compiles.com
    tapGui: tap-gui-build.tap.y-compiles.com
